### ISSUE TITLE
Copyright Infringement!

### ISSUE THREAD

**Issue by guillaume-chevalier** [healthDataScience/deep-learning-HAR#1]
Hi @bhimmetoglu , 

Your work is very interesting. I really like how you managed to crank the test accuracy up to 94.8% with the LSTM alone, that is interesting and remarkable. I have also made work about LSTMs for HAR. I think you forgot to cite my work, which is under the MIT License, Copyright (c) 2016 Guillaume Chevalier: https://github.com/guillaume-chevalier/LSTM-Human-Activity-Recognition/blob/master/LICENSE

I used the two stacked LSTM cells like you just did, on the same HAR dataset, and with TensorFlow, too. Overall, the part of you project where the LSTMs are used seems entirely: 
1. Copied from my project, 
2. Rewritten a bit differently, 
3. With a few improvements added.
Congratulations for achieving an accuracy of 94.8%!

The structure of the code in your project follows the same progression as my original code. I also see that you have put a star on my project and that [you were aware of it](https://github.com/bhimmetoglu?page=1&tab=stars&utf8=%E2%9C%93&q=lstm). Also, Some lines of code, as well as the unique comments on the logic of those lines are nearly identical to mines, such as for example here:
```
    lstm_in = tf.transpose(inputs_, [1,0,2]) # reshape into (seq_len, N, channels)
    lstm_in = tf.reshape(lstm_in, [-1, n_channels]) # Now (seq_len*N, n_channels)
```
Compared to my code: 
```
    # input shape: (batch_size, n_steps, n_input)
    _X = tf.transpose(_X, [1, 0, 2])  # permute n_steps and batch_size
    # Reshape to prepare input to hidden activation
    _X = tf.reshape(_X, [-1, n_input]) 
    # new shape: (n_steps*batch_size, n_input)
```

To cite my work, I at least ask to point to the URL of the homepage of the GitHub repository, as stated in the README.md of my project, such as: 
> Guillaume Chevalier, LSTMs for Human Activity Recognition, 2016 
> https://github.com/guillaume-chevalier/LSTM-Human-Activity-Recognition

For now:
- please cite my work in your GitHub repository's README.md: 
https://github.com/healthDataScience/deep-learning-HAR/blob/master/README.md
- and also please cite my work at the end of your article: 
https://burakhimmetoglu.com/2017/08/22/time-series-classification-with-tensorflow/

Please act quickly, your work is already copied and cited by others without citations to mine: 
- http://neuralsculpt.com/2017/08/23/time-series-classification-with-tensorflow/
- http://www.dataarchitect.cloud/time-series-classification-with-tensorflow/
- http://www.biva-ags.com/time-series-classification-with-tensorflow/

Citing someone is simple. Sorry for the trouble, and thanks in advance.

**Comment by bhimmetoglu** [comment]
Hi Guilamme,

Sorry for forgetting to cite you! I have completely forgotten to cite your work and it is a honest mistake. I have updated the Readme and I will also update my blog post.

I have also cite A. Saeed's work on CNNs (https://aqibsaeed.github.io/2016-11-04-human-activity-recognition-cnn/) which I have also forgotten by an honest mistake.

Thanks for reminding me. 

Regards,

**Comment by guillaume-chevalier** [comment]
My last name is "Chevalier", not "[Chavalier](http://www.urbandictionary.com/define.php?term=chavalier)" (please fix).

Thanks for the quick action, though.

Regards

**Comment by bhimmetoglu** [comment]
Sorry! Fixed..
